"""init

Revision ID: 0242f3fe5a37
Revises: 
Create Date: 2020-03-21 17:00:03.975547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '0242f3fe5a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # manual change: Mar 21 17:50
    op.execute(CreateSequence(Sequence('diary_id_seq')))
    op.execute(CreateSequence(Sequence('orderitem_id_seq')))
    op.execute(CreateSequence(Sequence('order_id_seq')))
    # end manual change: Mar 21 17:50
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('diary')
    # ### end Alembic commands ###
